import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "./components/MainNav";
import PageTransition from "./components/PageTransition";
import RectangleTransition from "./components/RectangleTransition";
import Gradient from "./components/Gradient";
import Header from "./components/Header";

import { Toaster } from "react-hot-toast";

const SometypeMono = Sometype_Mono({
  variable: "--font-sometypeMono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${SometypeMono.variable} antialiased overflow-hidden relative`}
      >
        <Gradient />
        <RectangleTransition />
        <PageTransition>
          <div className="flex">
            <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
              <MainNav />
            </div>
            <div className="w-full max-w-[1130px] px-[15px] mx-auto">
              <Header />
              <div>{children}</div>
            </div>
          </div>
        </PageTransition>
        <Toaster />
      </body>
    </html>
  );
}
